<a href="https://colab.research.google.com/github/cocoisland/DS-Sprint-03-Creating-Professional-Portfolios/blob/master/Reverse_engineering_SwitchUp's_ranks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reverse-engineering SwitchUp's ranks

Here's what SwitchUp says about their [ranking methodology](https://www.switchup.org/rankings/best-coding-bootcamps):

> SwitchUp's rankings are based on over 9,000 reviews from verified students and alumni, across over 300 schools in operation. Both the total review score and review count were weighted, and an internal algorithm was used to determine the ranking order. Because student and alumni feedback are indicative of bootcamp quality, review score was assigned a higher weight than review count.

## Scrape the data

In [0]:
import bs4
import pandas as pd
import requests

def scrape(url):
    result = requests.get(url)
    soup = bs4.BeautifulSoup(result.text, 'html.parser')
    schools = [a.text for a in soup.select('h3 a')]
    ratings = [float(span.text.split('/')[0]) for span in soup.select('.ranking-item__rating--value')]
    reviews = [int(a.text.split()[0]) for a in soup.select('.ranking-item__rating--count a')]
    ranks = range(1, len(schools)+1)
    data = pd.DataFrame({'rank': ranks, 'ratings': ratings, 'reviews': reviews}, index=schools)
    return data

overall = scrape('https://www.switchup.org/rankings/best-coding-bootcamps')
online = scrape('https://www.switchup.org/rankings/best-online-bootcamps')

In [0]:
overall

                                      rank  ratings  reviews
Le Wagon                                 1     4.97      651
Ironhack                                 2     4.86      498
App Academy                              3     4.70      480
General Assembly                         4     4.23      529
Bloc                                     5     4.80      274
Thinkful                                 6     4.74      207
Flatiron School                          7     4.89      182
HackerYou                                8     4.98      170
The Tech Academy                         9     4.80      163
Hack Reactor                            10     4.69      147
Tech Talent South                       11     4.70      140
Actualize                               12     4.89      125
Epicodus                                13     4.73      129
Startup Institute                       14     4.42      137
Makers Academy                          15     4.49      129
LambdaSchool                            16     4.97      116
BrainStation                            17     4.68      112
Coding Dojo                             18     4.17      120
Codesmith                               19     4.82       93
Code Fellows                            20     4.74       86
The Software Guild                      21     4.64       87
Tech Elevator                           22     4.87       79
Fullstack Academy                       23     4.88       76
Wyncode                                 24     4.72       78
Lighthouse Labs                         25     4.41       83
DigitalCrafts                           26     4.97       73
Skylab Coders Academy                   27     4.93       67
Galvanize                               28     4.14       79
Skillcrush                              29     4.55       71
Dev Mountain                            30     4.66       68
Ubiqum Code Academy                     31     4.85       59
LearningFuze                            32     4.96       56
CareerFoundry                           33     4.35       63
RED Academy                             34     4.53       58
Founders and Coders                     35     4.90       52
Code Institute                          36     4.62       53
Sabio                                   37     4.72       50
Horizons School of Technology           38     4.91       46
Dev League                              39     4.89       46
Turing School of Software and Design    40     4.82       45
Coding Temple                           41     4.98       43
Claim Academy                           42     4.33       49
Launch Academy                          43     4.41       48
devCodeCamp                             44     4.60       43
Coder Foundry                           45     4.60       42
Codeworks                               46     5.00       37
V School                                47     4.94       33
Neoland                                 48     4.84       32
Bitmaker Labs                           49     4.59       32
SE Factory                              50     4.90       30

In [0]:
online

                          rank  ratings  reviews
App Academy                  1     4.70      480
General Assembly             2     4.23      529
Bloc                         3     4.80      274
Thinkful                     4     4.74      207
Product School               5     4.78      187
Flatiron School              6     4.89      182
The Tech Academy             7     4.80      163
NYC Data Science Academy     8     4.87      148
Hack Reactor                 9     4.69      147
RMOTR                       10     4.91      133
Actualize                   11     4.89      125
LambdaSchool                12     4.97      116
Dataquest                   13     4.93      116
Springboard                 14     4.89      115
BrainStation                15     4.68      112
Coding Dojo                 16     4.17      120
Designlab                   17     4.72       98
Codesmith                   18     4.82       93
The Software Guild          19     4.64       87
Fullstack Academy           20     4.88       76
Galvanize                   21     4.14       79
Skillcrush                  22     4.55       71
Dev Mountain                23     4.66       68
Altcademy                   24     4.90       62
CareerFoundry               25     4.35       63
Metis                       26     4.89       54
Code Institute              27     4.62       53
First Step Coding           28     5.00       48
Evolve Security Academy     29     5.00       33
V School                    30     4.94       33
DataCamp                    31     4.56       32
Hyperion Development        32     4.71       31
The Firehose Project        33     5.00       28
Helio Training Bootcamp     34     4.63       30
Byte Academy                35     4.70       27
Level                       36     4.52       27
The Data Incubator          37     4.73       22
B9lab Academy               38     4.62       21
Bottega                     39     4.75       20
OpenClassrooms              40     4.88       16
CodingNomads                41     5.00       14
Science to Data Science     42     4.83       12
Codecademy                  43     4.11       14
BitDegree                   44     4.75       12
Design Sprint School        45     4.91       11
Make School                 46     4.82       11
Treehouse                   47     4.10       10

# Calculate "Spearman's rank correlation"

[Spearman's rank correlation coefficient](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient)

In [0]:
overall.corr(method='spearman')

             rank   ratings   reviews
rank     1.000000  0.005188 -0.992964
ratings  0.005188  1.000000 -0.094792
reviews -0.992964 -0.094792  1.000000

In [0]:
online.corr(method='spearman')

             rank   ratings   reviews
rank     1.000000 -0.054795 -0.997976
ratings -0.054795  1.000000  0.020950
reviews -0.997976  0.020950  1.000000